lang: en
author: Jürgen Ratzenböck
copyright: © 2017 Jürgen Ratzenböck
title: Jürgen's Dev Blog
description: Developer blog of Jürgen Ratzenböck
keywords: Blog,Dev,Developer,Web,Tech,Jürgen,Ratzenböck,Full-Stack
headline: Hi, I am Jürgen. I am a Software Developer and passionate about full-stack web technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jratzenboeck.com" # the base hostname & protocol for your site, e.g. http://example.com
email: juergen.ratzenboeck@gmail.com
github_account: https://github.com/ratzi199
facebook_account: https://facebook.com/jurgen.ratzenbock
xing_account: https://www.xing.com/profile/Juergen_Ratzenboeck
google_account: https://plus.google.com/u/0/101485925841247116853

# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
plugins:
  - jekyll-feed