lang: en
author: Jürgen Ratzenböck
copyright: © 2017 Jürgen Ratzenböck
title: Learn about full-stack web development - Jürgen's Dev Blog
description: This is the personal developer blog of Jürgen Ratzenböck. I am passionate about full-stack web development and blog about my latest experience.
keywords: Blog,Dev,Developer,Web,Tech,Jürgen,Ratzenböck,Full-Stack
headline: Hi, I am Jürgen. I am a Software Developer and passionate about full-stack web technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jratzenboeck.com" # the base hostname & protocol for your site, e.g. http://example.com
email: juergen.ratzenboeck@gmail.com
github_account: https://github.com/ratzi199
facebook_account: https://facebook.com/jurgen.ratzenbock
xing_account: https://www.xing.com/profile/Juergen_Ratzenboeck
google_account: https://plus.google.com/u/0/101485925841247116853
linkedin_account: https://www.linkedin.com/in/j%C3%BCrgen-ratzenb%C3%B6ck-221a9a14b/

# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true