lang: en
title: Jürgen's Dev Blog
author: Jürgen Ratzenböck
description: Hi, I am Jürgen. I am a Software Developer and passionate about full-stack web technologies.
baseurl: "/jratzenboeck-blog" # the subpath of your site, e.g. /blog
url: "https://ratzi199.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email: juergen.ratzenboeck@gmail.com
github_account: https://github.com/ratzi199
facebook_account: https://facebook.com/jurgen.ratzenbock
xing_account: https://www.xing.com/profile/Juergen_Ratzenboeck

# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
gems:
  - jekyll-feed